name: pre-release

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn package -Dmaven.deploy.skip=true
      
    - name: Get short hash
      id: short_sha
      run: echo "::set-output name=sha::$(expr substr ${{ github.sha }} 1 7)"
      
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: target/*.jar
        token: ${{ secrets.JAVA_TOKEN }}
        tag_name: staging-${{ steps.short_sha.outputs.sha }}
        release_name: pre-release ${{ steps.short_sha.outputs.sha }}
        body: |
          This is an automatic pre-release build of commit ${{ github.sha }}
          With this release you can test ahead of time the next ZC-Bot release candidate
        draft: false
        prerelease: true
